name: Building chromium 
on: workflow_dispatch
env:
  vs2022_install: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'
  DEPOT_TOOLS_WIN_TOOLCHAIN: "0"
  GITUSER: ${{ secrets.GITUSER }}
  GITMAIL: ${{ secrets.GITMAIL }}
  CHROMIUM_PATH: 'C:\chromium'
  DEPOT_TOOLS_URI: "https://storage.googleapis.com/chrome-infra/depot_tools.zip"
  DEPOT_TOOLS_PATH: 'C:\depot_tools'
  SCCACHE_FILENAME: "sccache-v0.4.2-x86_64-pc-windows-msvc"
  SCCACHE_URI: "https://github.com/mozilla/sccache/releases/download/v0.4.2/sccache-v0.4.2-x86_64-pc-windows-msvc.tar.gz"
  SCCACHE_TOOL_PATH: 'C:\sccache-v0.4.2-x86_64-pc-windows-msvc'
  SCCACHE_DIR: 'C:\sccache'
  SCCACHE_CACHE_SIZE: '20G'

jobs:
  build-1:
    runs-on: windows-2022
    
    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Pre Volume Details
        run: Get-Volume
      
      - name: Setup Build Tools
        run: python3 .\scripts\setup-build-tools.py

      - name: Fetch Chromium
        run: .\scripts\fetch-chromium.ps1

      - name: Post Volume Details
        run: Get-Volume

      - name: Build
        id: build
        run: python3 .\scripts\build-chromium.py
     
      - name: Upload Partial Built Chromium
        if: ${{ steps.build.outputs.finished != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: "${{ env.CHROMIUM_PATH }}.zip"
        
      - name: Upload Sccache Cache
        if: ${{ steps.build.outputs.finished == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.SCCACHE_DIR }}.zip"
    

  build-2:
    if: ${{ needs.build-1.outputs.finished != 'true' }}
    needs: build-1
    runs-on: windows-2022

    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Build Tools
        run: python3 .\scripts\setup-build-tools.py

      # Reuse artifact from previou job. This also avoid the need to checkout 
      # source code again, helps in incremental build.
      - name: Download Partially Built Chromium 
        uses: actions/download-artifact@v3
        with:
          name: chromium
          path: "C:\\chromium.zip" 
 
      - name: Build
        id: build
        run: python3 .\scripts\build-chromium.py

      - name: Volume Details
        run: Get-Volume

      - name: Display Cache Stats
        run: >
          "$((Get-ChildItem ${{ env.SCCACHE_DIR }} | Measure-Object -Property Length -Sum).Sum/1MB) in MB"

      - name: Upload Partial Built Chromium
        if: ${{ steps.build.outputs.finished != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: "${{ env.CHROMIUM_PATH }}.zip"
        
      - name: Upload Sccache Cache
        if: ${{ steps.build.outputs.finished == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.SCCACHE_DIR }}.zip"

      # - name: Release Sccache Cache 
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: ${{ env.SCCACHE_DIR }} 

  build-3:
    if: ${{ needs.build-2.outputs.finished != 'true' }}
    needs: build-2
    runs-on: windows-2022

    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Build Tools
        run: python3 .\scripts\setup-build-tools.py

      # Reuse artifact from previous job. This also avoid the need to checkout 
      # source code again, helps in incremental build.
      - name: Download Partially Built Chromium 
        uses: actions/download-artifact@v3
        with:
          name: chromium
          path: "${{ env.CHROMIUM_PATH }}.zip" 

      - name: Build
        id: build
        run: python3 .\scripts\build-chromium.py

      - name: Volume Details
        run: Get-Volume

      - name: Display Cache Stats
        run: >
          "$((Get-ChildItem ${{ env.SCCACHE_DIR }} | Measure-Object -Property Length -Sum).Sum/1MB) in MB"

      - name: Upload Partial Built Chromium
        if: ${{ steps.build.outputs.finished != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: "${{ env.CHROMIUM_PATH }}.zip"
        
      - name: Upload Sccache Cache
        if: ${{ steps.build.outputs.finished == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.SCCACHE_DIR }}.zip"
