name: Building chromium 
on: workflow_dispatch
jobs:
  build-chromium:
    permissions:
      contents: write
    name: build
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Build
        run: >
          .\scripts\run.ps1 -GitUser "{{ SECRETS.GITUSER }}"
          -GitMail "{{ SECRETS.GITMAIL }}"

      - name: Start Build
        working-directory: chromium\src
        run: autoninja -C out\Default chrome
        env:
          PATH: ${{ env.PATH }}
          DEPOT_TOOLS_WIN_TOOLCHAIN: "0"
          vs2022_install: ${{ env.vs2022_install }}
          SCCACHE_CACHE_SIZE: "20G"
          SCCACHE_DIR: 'chromium\sccache'

      - name: Display Cache Stats
        run: >
          "$((Get-ChildItem chromium\sccache | Measure-Object -Property Length -Sum).Sum/1MB) in MB"

      - name: Release Sccache Cache 
        uses: softprops/action-gh-release@v1
        with:
          files: chromium\sccache
