name: Building chromium 
on: workflow_dispatch
env:
  vs2022_install: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'
  DEPOT_TOOLS_WIN_TOOLCHAIN: "0"
  GITUSER: ${{ secrets.GITUSER }}
  GITMAIL: ${{ secrets.GITMAIL }}
  CHROMIUM_PATH: 'C:\chromium'
  DEPOT_TOOLS_URI: "https://storage.googleapis.com/chrome-infra/depot_tools.zip"
  DEPOT_TOOLS_PATH: 'C:\depot_tools'
  SCCACHE_FILENAME: "sccache-v0.4.2-x86_64-pc-windows-msvc"
  SCCACHE_URI: "https://github.com/mozilla/sccache/releases/download/v0.4.2/sccache-v0.4.2-x86_64-pc-windows-msvc.tar.gz"
  SCCACHE_TOOL_PATH: 'C:\sccache-v0.4.2-x86_64-pc-windows-msvc'
  SCCACHE_DIR: 'C:\sccache'
  SCCACHE_CACHE_SIZE: '20G'
  ARTIFACT_DIR: "C:\\artifacts"

jobs:
  build-1:
    runs-on: windows-2022
    
    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Pre Volume Details
        run: Get-Volume

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          key: build-cache-${{ github.run_id}}
          path: |
            ${{ env.DEPOT_TOOLS_PATH }}
            "${{ env.CHROMIUM_PATH }}.zip"
            ${{ env.SCCACHE_TOOL_PATH }}
      
      - name: Setup build tools and fetch Chromium
        if: steps.cache.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          python3 .\scripts\setup-build-tools.py
          $env:PATH="${{ env.DEPOT_TOOLS_PATH }};$env:PATH;${{ env.SCCACHE_TOOL_PATH }}"
          .\scripts\fetch-chromium.ps1

      - name: Post Volume Details
        run: Get-Volume

      - name: Extract, Build, Archive
        id: build
        run: python3 .\scripts\build-chromium.py
     
      - name: Upload Sccache Cache
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.ARTIFACT_DIR }}\\sccache.zip"

  build-2:
    if: ${{ needs.build-1.outputs.finished != 'true' }}
    needs: build-1
    runs-on: windows-2022

    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pre Volume Details
        run: Get-Volume

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          key: build-cache-${{ github.run_id}}
          path: |
            ${{ env.DEPOT_TOOLS_PATH }}
            "${{ env.CHROMIUM_PATH }}.zip"
            ${{ env.SCCACHE_TOOL_PATH }}
      
      # fail job if cache miss
      - name: Check Cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Setup Envs
        run: |
          echo "${{ env.DEPOT_TOOLS_PATH }}" >> "$env:GITHUB_ENV"
          echo "${{ env.SCCACHE_TOOL_PATH }}" >> "$env:GITHUB_ENV"

      - name: Download Sccache Cache
        uses: actions/download-artifact@v3
        with:
          name: sccache-cache
          path: ${{ env.ARTIFACT_DIR }}
        
      - name: Extract, Build, Archive
        id: build
        run: python3 .\scripts\build-chromium.py

      - name: Volume Details
        run: Get-Volume

      - name: Upload Sccache Cache
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.ARTIFACT_DIR }}\\sccache.zip"

  build-3:
    if: ${{ needs.build-2.outputs.finished != 'true' }}
    needs: build-2
    runs-on: windows-2022

    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          key: build-cache-${{ github.run_id}}
          path: |
            ${{ env.DEPOT_TOOLS_PATH }}
            "${{ env.CHROMIUM_PATH }}.zip"
            ${{ env.SCCACHE_TOOL_PATH }}
      
      # fail job if cache miss
      - name: Check Cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Setup Envs
        run: |
          echo "${{ env.DEPOT_TOOLS_PATH }}" >> "$env:GITHUB_ENV"
          echo "${{ env.SCCACHE_TOOL_PATH }}" >> "$env:GITHUB_ENV"

      - name: Download Sccache Cache
        uses: actions/download-artifact@v3
        with:
          name: sccache-cache
          path: ${{ env.ARTIFACT_DIR }}

      - name: Build
        id: build
        run: python3 .\scripts\build-chromium.py

      - name: Volume Details
        run: Get-Volume

      - name: Upload Sccache Cache
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.ARTIFACT_DIR }}\\sccache.zip"

  build-4:
    if: ${{ needs.build-3.outputs.finished != 'true' }}
    needs: build-3
    runs-on: windows-2022

    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Build Tools
        run: python3 .\scripts\setup-build-tools.py

      # Reuse artifact from previous job. This also avoid the need to checkout 
      # source code again, helps in incremental build.
      - name: Download Partially Built Chromium
        uses: actions/download-artifact@v3
        with:
          name: chromium
          path: ${{ env.ARTIFACT_DIR }}

      - name: Download Sccache Cache
        uses: actions/download-artifact@v3
        with:
          name: sccache-cache
          path: ${{ env.ARTIFACT_DIR }}

      - name: Build
        id: build
        run: python3 .\scripts\build-chromium.py

      - name: Volume Details
        run: Get-Volume

      - name: Upload Sccache Cache
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.ARTIFACT_DIR }}\\sccache.zip"

      - name: Upload Partial Built Chromium
        if: ${{ steps.build.outputs.finished != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: "${{ env.ARTIFACT_DIR }}\\chromium.zip"


  build-5:
    if: ${{ needs.build-4.outputs.finished != 'true' }}
    needs: build-4
    runs-on: windows-2022

    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Build Tools
        run: python3 .\scripts\setup-build-tools.py

      # Reuse artifact from previous job. This also avoid the need to checkout 
      # source code again, helps in incremental build.
      - name: Download Partially Built Chromium
        uses: actions/download-artifact@v3
        with:
          name: chromium
          path: ${{ env.ARTIFACT_DIR }}

      - name: Download Sccache Cache
        uses: actions/download-artifact@v3
        with:
          name: sccache-cache
          path: ${{ env.ARTIFACT_DIR }}

      - name: Build
        id: build
        run: python3 .\scripts\build-chromium.py

      - name: Volume Details
        run: Get-Volume

      - name: Upload Sccache Cache
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.ARTIFACT_DIR }}\\sccache.zip"

      - name: Upload Partial Built Chromium
        if: ${{ steps.build.outputs.finished != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: "${{ env.ARTIFACT_DIR }}\\chromium.zip"

  build-6:
    if: ${{ needs.build-5.outputs.finished != 'true' }}
    needs: build-5
    runs-on: windows-2022

    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Build Tools
        run: python3 .\scripts\setup-build-tools.py

      # Reuse artifact from previous job. This also avoid the need to checkout 
      # source code again, helps in incremental build.
      - name: Download Partially Built Chromium
        uses: actions/download-artifact@v3
        with:
          name: chromium
          path: ${{ env.ARTIFACT_DIR }}

      - name: Download Sccache Cache
        uses: actions/download-artifact@v3
        with:
          name: sccache-cache
          path: ${{ env.ARTIFACT_DIR }}

      - name: Build
        id: build
        run: python3 .\scripts\build-chromium.py

      - name: Volume Details
        run: Get-Volume

      - name: Upload Sccache Cache
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.ARTIFACT_DIR }}\\sccache.zip"

      - name: Upload Partial Built Chromium
        if: ${{ steps.build.outputs.finished != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: "${{ env.ARTIFACT_DIR }}\\chromium.zip"

  build-7:
    if: ${{ needs.build-6.outputs.finished != 'true' }}
    needs: build-6
    runs-on: windows-2022

    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Build Tools
        run: python3 .\scripts\setup-build-tools.py

      # Reuse artifact from previous job. This also avoid the need to checkout 
      # source code again, helps in incremental build.
      - name: Download Partially Built Chromium
        uses: actions/download-artifact@v3
        with:
          name: chromium
          path: ${{ env.ARTIFACT_DIR }}

      - name: Download Sccache Cache
        uses: actions/download-artifact@v3
        with:
          name: sccache-cache
          path: ${{ env.ARTIFACT_DIR }}

      - name: Build
        id: build
        run: python3 .\scripts\build-chromium.py

      - name: Volume Details
        run: Get-Volume

      - name: Upload Sccache Cache
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.ARTIFACT_DIR }}\\sccache.zip"

      - name: Upload Partially Built Chromium
        if: ${{ steps.build.outputs.finished != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: "${{ env.ARTIFACT_DIR }}\\chromium.zip"

  build-8:
    if: ${{ needs.build-7.outputs.finished != 'true' }}
    needs: build-7
    runs-on: windows-2022

    outputs:
      finished: ${{ steps.build.outputs.finished }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Build Tools
        run: python3 .\scripts\setup-build-tools.py

      # Reuse artifact from previous job. This also avoid the need to checkout 
      # source code again, helps in incremental build.
      - name: Download Partially Built Chromium
        uses: actions/download-artifact@v3
        with:
          name: chromium
          path: ${{ env.ARTIFACT_DIR }}


      - name: Download Sccache Cache
        uses: actions/download-artifact@v3
        with:
          name: sccache-cache
          path: ${{ env.ARTIFACT_DIR }}

      - name: Build
        id: build
        run: python3 .\scripts\build-chromium.py

      - name: Volume Details
        run: Get-Volume

      - name: Upload Sccache Cache
        uses: actions/upload-artifact@v3
        with:
          name: sccache-cache
          path: "${{ env.ARTIFACT_DIR }}\\sccache.zip"

      - name: Upload Partial Built Chromium
        if: ${{ steps.build.outputs.finished != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: chromium
          path: "${{ env.ARTIFACT_DIR }}\\chromium.zip"
 
