name: Setup MSVC
on: workflow_dispatch
env:
  MSVC_INSTALLER: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'

jobs:
  setup-msvc-community:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup msvc
        run: ./scripts/setup-msvc.ps1

      - name: Test
        run: |
          Start-Process pwsh -ArgumentList 'echo $env:username'
          echo "after admin run"
          echo "echo $env:username"

      - name: Volume Details
        run: Get-Volume