name: Setup MSVC
on: workflow_dispatch
env:
  MSVC_INSTALLER: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'

jobs:
  setup-msvc-community:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Install gsudo
        run: choco install gsudo

      - name: setup msvc
        run: sudo ./scripts/setup-msvc.ps1

      - name: Volume Details
        run: Get-Volume